package dev.skrety.sftoolkit.schema

/**
 * Generates Apex "faux classes" from org describes — the same mechanism
 * salesforcedx-vscode uses so the Apex Language Server completes sObject fields.
 * Files land under <sfdx>/.sfdx/tools/sobjects/{standardObjects|customObjects}/,
 * which the LS indexes and every standard SFDX .gitignore excludes.
 */
object FauxClassGenerator {

    // Salesforce field type → Apex type (mirrors the VS Code faux-class generator).
    private val APEX_TYPES = mapOf(
        "string" to "String", "textarea" to "String", "phone" to "String",
        "url" to "String", "email" to "String", "picklist" to "String",
        "multipicklist" to "String", "combobox" to "String", "encryptedstring" to "String",
        "boolean" to "Boolean",
        "int" to "Integer",
        "double" to "Double", "percent" to "Double",
        "currency" to "Decimal",
        "date" to "Date",
        "datetime" to "Datetime",
        "time" to "Time",
        "id" to "Id",
        "base64" to "Blob",
        "anyType" to "Object", "anytype" to "Object", "complexvalue" to "Object",
        "location" to "Location",
        "address" to "Address",
    )

    fun isCustom(objectName: String): Boolean = objectName.contains("__")

    /** One faux class per object; relationship fields typed to their target (SObject when polymorphic). */
    fun generate(schema: ObjectSchema): String = buildString {
        appendLine("// Generated by SF Toolkit from the org describe. Do not edit —")
        appendLine("// regenerated by \"Generate Apex sObject Definitions\". Lives under .sfdx/ (untracked).")
        appendLine("global class ${schema.name} {")
        for (field in schema.fields) {
            if (field.relationshipName != null && field.referenceTo.isNotEmpty()) {
                val target = if (field.referenceTo.size == 1) field.referenceTo.first() else "SObject"
                appendLine("    global $target ${field.relationshipName};")
            }
            val apexType = when {
                field.type.equals("reference", ignoreCase = true) -> "Id"
                else -> APEX_TYPES[field.type.lowercase()] ?: "String"
            }
            appendLine("    global $apexType ${field.name};")
        }
        appendLine("}")
    }
}
